import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { Experience, Skills } from "./types";

interface ProfileState {
  profileJobTitle: string;
  profileSkills: Skills;
  profileExperiences: Experience[];
  defaultCheckedExperiences: number[];
  profileIntroduction: string;
}

const initialState: ProfileState = {
  profileJobTitle: "React Typescript Developer",
  profileSkills: {
    technical: [
      "React",
      "TypeScript",
      "OOP",
      "CRUD",
      "JavaScript",
      "Redux",
      "Saga",
      "WebSockets",
      "React Query",
      "Redux Thunk",
      "React Forms",
      "Jest",
      "RTL",
      "Next",
      "Storybook",
      "Material-UI",
      "Chakra UI",
      "Git",
      "CI/CD",
      "Docker",
      "PHP",
      "Google Analytics",
      "Framer Motion",
      "Three.js",
      "Fabric.js",
      "Canvas API",
      "Formik",
      "Yup",
      "MUI",
      "Rollup",
      "NPM",
      "Webpack",
      "Figma",
    ],
    soft: [
      "Problem-solving",
      "Self-Motivated",
      "Forward-Thinking",
      "Detail-Oriented",
    ],
  },
  profileIntroduction:
    "I'm a React TypeScript Developer with 6 years of experience creating dynamic and scalable applications. Throughout my career, I've successfully led projects and migrations, from reimagining user interfaces to optimizing performance and scalability. I thrive on problem-solving and pushing the boundaries of what's possible, always looking for innovative solutions. My passion lies in turning complex challenges into intuitive, user-friendly products that drive results.",
  defaultCheckedExperiences: [1, 2],
  profileExperiences: [
    {
      id: 1,
      label: "Web4Realty",
      title: "Lead ReactJS Developer",
      company: "Web4Realty",
      hireType: "Contract",
      dateFrom: "Mar 2024",
      dateTo: "May 2024",
      prompt: "Prompt for experience 1",
      location: "USA based",
      bulletPoints: [
        "Led frontend development for a CMS, achieving a 80% improvement in page load times through code splitting, lazy loading, server-side rendering (SSR) with Next.js, and caching strategies.",
        "Enhanced UI responsiveness and stability with modular development practices for highly dynamic, customizable components and widgets, crucial to a CMS.",
        "Designed responsive layouts using advanced CSS techniques, including Flexbox, Grid, and media queries, ensuring adaptability across various devices and accommodating user-defined component configurations",
        "Ensured flawless functionality by testing numerous user-defined configurations with Jest and RTL, often managing up to 25 variations simultaneously.",
      ],
      project: "Web4Realty",
    },
    {
      id: 2,
      label: "Droptrack",
      title: "React Typescript Developer",
      company: "Glofy",
      location: "USA Based",
      dateFrom: "October 2023",
      dateTo: "February 2024",
      project: "Droptrack",
      prompt: "Prompt for experience 2",
      hireType: "Contract",
      bulletPoints: [
        "Demonstrated adaptability and strong problem-solving skills by migrating from PHP to React.",
        "Built a React-based media player using RESTful APIs for dynamic streaming and AI-powered data fetching.",
        "Translated Figma mock-ups into fully functional React features, ensuring a responsive UI.",
        "Enhanced user experience by implementing multistep forms, leveraging state management tools such custom hooks, Context API and Redux.",
      ],
    },
    {
      id: 3,
      label: "Ingram Spark",
      title: "React Typescript Developer",
      company: "WeDevelop",
      dateFrom: "August 2023",
      dateTo: "October 2023",
      prompt: "Prompt for experience 3",
      bulletPoints: [
        "Collaborated developing a real-time book cover design editor with React TypeScript, Fabric.js, Websockets, Saga, and Canvas API in a cross-functional team.",
        "Contributed to the development of scalable architecture with OOP principles, ensuring maintainable code.",
        "Participated in rigorous code reviews, providing constructive feedback and promoting continuous improvement in an agile environment.",
      ],
      project: "Ingram Spark",
      location: "USA Based",
      hireType: "Contract",
    },
    {
      id: 4,
      label: "Outbound Engine",
      title: "ReactJS Developer",
      company: "WeDevelop",
      dateFrom: "July 2022",
      dateTo: "August 2023",
      prompt: "Prompt for experience 3",
      bulletPoints: [
        "Led the migration of a real estate CMS and social media platform from ExtJS to React, significantly improving UI performance and scalability.",
        "Developed and maintained a UI component library using Rollup, NPM, Webpack, and Storybook, ensuring consistency and reusability across projects.",
        "Collaborated closely with clients to enhance feature functionality and improve user experience, ensuring project goals were met and exceeded.",
      ],
      project: "Outbound Engine",
      location: "USA Based",
      hireType: "Contract",
    },
    {
      id: 5,
      label: "Claro",
      title: "Lead ReactJS Developer",
      company: "CFOTech",
      dateFrom: "May 2021",
      dateTo: "December 2021",
      prompt: "Prompt for experience 3",
      bulletPoints: [
        "Managed the full lifecycle of the CLARO project, including ticket creation, workflow management, and ensuring timely project delivery.",
        "Developed complex forms using Formik and Yup, implementing advanced validation techniques to ensure accuracy and user satisfaction.",
      ],
      project: "Claro",
      location: "Argentina",
      hireType: "Employee",
    },
    {
      id: 6,
      label: "Triple A",
      title: "ReactJS Developer",
      company: "Baufest",
      dateFrom: "June 2019",
      dateTo: "May 2021",
      prompt: "Prompt for experience 3",
      bulletPoints: [
        "Liaised with clients at Triple A to design and implement CRUD operations in MUI tables, improving data management and reporting capabilities.",
        "Integrated Google Analytics to track and optimize user behavior, leading to improved product performance and user engagement.",
      ],
      project: "Triple A",
      location: "USA Based",
      hireType: "Employee",
    },
    {
      id: 7,
      label: "American Logistics",
      title: "Frontend Developer ReactJS",
      company: "Baufest",
      dateFrom: "June 2019",
      dateTo: "May 2021",
      prompt: "Prompt for experience 3",
      bulletPoints: [
        "Developed an accessibility-focused page for users with disabilities, ensuring compliance through semantic HTML, ARIA labels, and rigorous accessibility testing.",
        "Utilized Redux Saga to manage state and orchestrate asynchronous operations within a multistep form.",
        "Integrated real-time car tracking and ETA calculations using Google Maps and Google Places API, utilizing Redux Saga for fast-updating systems catering to people with disabilities.",
        "Maintained and developed Storybook components.",
      ],
      project: "American Logistics",
      location: "USA Based",
      hireType: "Employee",
    },
    {
      id: 8,
      label: "Camuzzi Gas",
      title: "Full Stack Developer .NET | Angular",
      company: "Baufest",
      dateFrom: "November 2018",
      dateTo: "June 2019",
      prompt: "Prompt for experience 3",
      bulletPoints: [
        "Began my career as a developer after being selected from a competitive bootcamp process, out of 20 candidates.",
        "Thrived in a fast-paced environment that demanded self-teaching and autonomous research.",
        "Contributed to more than 80 backlog items, collaborating as a key team member at Camuzzi Gas, enhancing system capabilities and functionality.",
        "Gained experience in cross-platform technologies and worked with Cordova to extend the reach of applications across different platforms.",
      ],
      project: "Camuzzi Gas",
      location: "Argentina",
      hireType: "Employee",
    },
    {
      id: 9,
      label: "StreamCoder",
      title: "React Typescript Engineer - Leader - UX",
      company: "StreamCoder",
      dateFrom: "July 2021",
      dateTo: "Present",
      prompt: "Prompt for experience 3",
      bulletPoints: [
        "Envisioned and led the development of StreamCoder CMS, a platform for custom dynamic OBS widgets tailored for live streamers.",
        "Designed and implemented interactive overlays and integrations using React, TypeScript, Redux Saga, WebSockets, Node.js, and the Twitch API, enhancing live streaming experiences.",
        "Developed a Storybook plugin to improve Chakra UI theme management and facilitate design consistency across applications.",
        "Mentored junior developers while designing responsive UI components in Figma and ensuring best practices in UI/UX design.",
      ],
      project: "StreamCoder",
      location: "Remote",
      hireType: "Self-Employed",
    },
  ],
};

const profileSlice = createSlice({
  name: "profile",
  initialState,
  reducers: {
    setProfile: (state, action: PayloadAction<Partial<ProfileState>>) => {
      state = { ...state, ...action.payload };
    },
  },
});

export const { setProfile } = profileSlice.actions;
export const profileReducer = profileSlice.reducer;
